version: '3'
services:
  proxy:
    image: nginx
    container_name: nginx-proxy
    depends_on:
      - frontend
      - backend
    ports:
      - 80:80
    restart: always
    volumes:
      - ./nginx/test.conf:/etc/nginx/sites-available/test.conf
      - ./logs:/var/log/nginx
  
  internal-frontend:  
    image: internal-frontend
    build:
        dockerfile: ./internal-frontend/Dockerfile
    container_name: internal-frontend
    # depends_on:
    #   - 
    # ports:
    #   - :
    restart: always
    volumes:
      - 
  external-frontend:
    image: external-frontend
    build:
        dockerfile: ./external-frontend/Dockerfile
    container_name: external-frontend
    # depends_on:
    #   - 
    # ports:
    #   - :
    restart: always
    volumes:

  internal-backend:
    image: internal-backend
    build:
        dockerfile: ./internal-backend/Dockerfile
    container_name: internal-backend
    # depends_on:
    #   - 
    # ports:
    #   - :
    restart: always
    volumes:
      - 
  external-backend:
    image: external-backend
    build:
        dockerfile: ./external-backend/Dockerfile
    container_name: external-backend
    depends_on:
      - 
    # ports:
    #   - :
    restart: always
    volumes:

  database:
    image: database
    build:
        dockerfile: ./database/Dockerfile
    container_name: database
    depends_on:
      - frontend
      - backend
    ports:
      -  : 
    restart: always
    volumes:
      - 
